version: 2

models:
  - name: new_table_query
    description: "A dbt model combinig icu_stays and hospital admissions"
    columns:
      - name: subject_id
        description: "The primary key for this table is subject_id"
        tests:
          - not_null
